apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-controlplane
spec:
  profile: {{.Values.istioProfile}}
  components:
    ingressGateways:
    - enabled: true
      name: {{.Values.devIngress.name}}
      namespace: {{.Values.ingressNamespace}}
      k8s:
        serviceAnnotations:
          cloud.google.com/load-balancer-type: {{ .Values.devIngress.loadBalancerType }}
        service:
          type: LoadBalancer
          loadBalancerIP: {{ .Values.devIngress.loadBalancerIP }}
          ports:
            - name: status-port
              port: 15021
              targetPort: 15021
            - name: http2
              port: 80
              targetPort: 8080
            - name: https
              port: 443
              targetPort: 8443
            - name: tls
              port: 15443
              targetPort: 15443
      label:
        istio: dev-ingressgateway
    - enabled: true
      name: {{.Values.mainIngress.name}}
      namespace: {{.Values.ingressNamespace}}
      k8s:
        serviceAnnotations:
          cloud.google.com/load-balancer-type: {{ .Values.mainIngress.loadBalancerType }}
        service:
          type: LoadBalancer
          loadBalancerIP: {{ .Values.mainIngress.loadBalancerIP }}
          ports:
            - name: https
              port: 443
              targetPort: 8443
      label:
        istio: main-ingressgateway
    - enabled: true
      name: {{.Values.extIngress.name}}
      namespace: {{.Values.ingressNamespace}}
      k8s:
        serviceAnnotations:
          cloud.google.com/load-balancer-type: {{ .Values.extIngress.loadBalancerType }}
        service:
          type: LoadBalancer
          loadBalancerIP: {{ .Values.extIngress.loadBalancerIP }}
          ports:
            - name: https
              port: 443
              targetPort: 8443
      label:
        istio: ext-ingressgateway
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
