apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: prometheus
    namespace: monitoring
spec:
    destination:
        namespace: prometheus-operator
        server: https://kubernetes.default.svc
    project: default
    source:
        repoURL: 'https://github.com/prometheus-operator/kube-prometheus.git'
        path: .
        targetRevision: master
    syncOptions:
        - CreateNamespace=true