apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-kubevious
  # annotations:
  #   argocd.argoproj.io/sync-wave: "3"
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubevious
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://helm.kubevious.io
    targetRevision: 0.7.22
    chart: kubevious
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true