apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingressrules
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: istio-ingress-rules
    repoURL: https://github.com/Coder63/argocd.git
    targetRevision: {{ .Values.spec.source.targetRevision }}
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true