apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-istio-base
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: manifests/charts/base
    repoURL: https://github.com/istio/istio.git
    targetRevision: 1.7.4
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true