apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-istio-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-operator
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: istio/operator
    repoURL: https://github.com/Coder63/argocd.git
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
