apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-certmanager
  # annotations:
  #   argocd.argoproj.io/sync-wave: "3"
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: deploy/charts/cert-manager
    repoURL: https://github.com/jetstack/cert-manager.git
    targetRevision: v1.0.4
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true