apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: minimal
  components:
    ingressGateways:
    - enabled: true
      name: dev-istio-ingressgateway
      namespace: istio-system
      k8s:
        serviceAnnotations:
          cloud.google.com/load-balancer-type: External
  addonComponents:
    grafana:
      enabled: true
    prometheus:
      enabled: true
    kiali:
      enabled: true
    zipkin:
      enabled: true