apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: default
  addonComponents:
    grafana:
      enabled: true
    prometheus:
      enabled: true
    kiali:
      enabled: true
    zipkin:
      enabled: true
  components:
    ingressGateways:
    - enabled: true
      name: dev-istio-ingressgateway
      namespace: istio-system
      k8s:
        serviceAnnotations:
          cloud.google.com/load-balancer-type: External
    - enabled: true 
      name: main-istio-ingressgateway
      namespace: istio-system
      k8s:
        serviceAnnotations:
          cloud.google.com/load-balancer-type: External

          kubectl get namespace "istio-system" -o json | tr -d "\n" | sed "s/\"finalizers\": \[[^]]\+\]/\"finalizers\": []/" | kubectl replace --raw /api/v1/namespaces/stucked-namespace/finalize -f -