# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret
  labels:
    app: application
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  credentials.json: {{ .Values.googleServiceAccount.credentials | b64enc | quote }}