---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: prom-gateway
spec:
  selector:
    istio: ext-ingressgateway
  servers:
    - hosts:
        - prom.istio.com
      port:
        number: 9090
        name: http
        protocol: HTTP
      tls:
       httpsRedirect: true
    - hosts:
        - prom.istio.com
      port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-vs
spec:
  hosts:
  - prom.istio.com
  gateways:
  - prom-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: prometheus-k8s.monitoring.svc.cluster.local
        port:
          number: 9090
