apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: selfsigning-issuer
  namespace: istio-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: istio-ingress-tls
    namespace: istio-system
spec:
    secretName: istio-ingress-tls
    dnsNames:
    - "*.svc.cluster.local"
    - "*.staging.donut.com"
    - "staging.donut.com"
    issuerRef:
    name: selfsigned-issuer