apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: argocd-vs
spec:
    hosts:
    - "argocd.staging.donut.com"
    gateways:
    - donutgateway
    tls:
    - match:
      - port: 443
        sniHosts:
        - argocd.staging.donut.com
      route:
      - destination:
           host: argocd-server.argocd.svc.cluster.local
           port:
             number: 443
---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#     name: argocd-vs
# spec:
#     hosts:
#     - "kubevious.staging.donut.com"
#     gateways:
#     - donutgateway
#     tls:
#     - match:
#         - port: 443
#         route:
#         - destination:
#             host: kubevious.kubevious.svc.cluster.local
#             port:
#                 number: 80
            